#!/usr/bin/env bats

# Steam's macOS shortcut for a game is a tiny shell launcher whose bundle
# size is not the installed game size. Mole should label these bundles as
# Steam-managed instead of presenting the shortcut size as the app size.

setup_file() {
    PROJECT_ROOT="$(cd "${BATS_TEST_DIRNAME}/.." && pwd)"
    export PROJECT_ROOT
}

setup() {
    HOME="$(mktemp -d "${BATS_TEST_DIRNAME}/tmp-steam-launcher.XXXXXX")"
    export HOME
    if [[ "$HOME" != "${BATS_TEST_DIRNAME}/tmp-"* ]]; then
        printf 'FATAL: HOME is not a test temp dir: %s\n' "$HOME" >&2
        return 1
    fi
    export TERM="dumb"
}

teardown() {
    if [[ "$HOME" == "${BATS_TEST_DIRNAME}/tmp-"* ]]; then
        rm -rf "$HOME"
    fi
}

create_steam_launcher_app() {
    local app_path="$1"
    local app_id="$2"
    mkdir -p "$app_path/Contents/MacOS"
    cat > "$app_path/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleIdentifier</key>
    <string>com.example.steamgame</string>
    <key>CFBundleExecutable</key>
    <string>SteamGame</string>
</dict>
</plist>
PLIST
    cat > "$app_path/Contents/MacOS/SteamGame" <<SH
#!/bin/bash
# autogenerated file - do not edit
open steam://run/$app_id
SH
    chmod +x "$app_path/Contents/MacOS/SteamGame"
}

create_regular_app() {
    local app_path="$1"
    mkdir -p "$app_path/Contents/MacOS"
    cat > "$app_path/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleIdentifier</key>
    <string>com.example.RegularApp</string>
    <key>CFBundleExecutable</key>
    <string>RegularApp</string>
</dict>
</plist>
PLIST
    cat > "$app_path/Contents/MacOS/RegularApp" <<SH
#!/bin/bash
open https://example.com
SH
    chmod +x "$app_path/Contents/MacOS/RegularApp"
}

sourceable_uninstall_sh() {
    local out="$1"
    awk -v script_dir="$PROJECT_ROOT/bin" '
        /^SCRIPT_DIR=/ { print "SCRIPT_DIR=\"" script_dir "\""; next }
        /main "\$@"/ { print "# main skipped by test"; next }
        { print }
    ' "$PROJECT_ROOT/bin/uninstall.sh" > "$out"
}

@test "uninstall_steam_launcher_appid extracts the app id from a Steam shortcut script" {
    app="$HOME/Applications/SteamGame.app"
    create_steam_launcher_app "$app" "1091500"

    run env HOME="$HOME" /bin/bash --noprofile --norc <<'EOF'
set -euo pipefail
source "$PROJECT_ROOT/lib/uninstall/steam.sh"
uninstall_steam_launcher_appid "$HOME/Applications/SteamGame.app"
EOF

    [ "$status" -eq 0 ]
    [[ "$output" == "1091500" ]]
}

@test "uninstall_steam_launcher_appid accepts rungameid and launch URL forms" {
    run env HOME="$HOME" PROJECT_ROOT="$PROJECT_ROOT" /bin/bash --noprofile --norc <<'EOF'
set -euo pipefail
source "$PROJECT_ROOT/lib/uninstall/steam.sh"
for url in "open steam://rungameid/1091500" "open steam://launch/1091500"; do
    dir="$HOME/App.app"
    mkdir -p "$dir/Contents/MacOS"
    printf '#!/bin/bash\n%s\n' "$url" > "$dir/Contents/MacOS/App"
    chmod +x "$dir/Contents/MacOS/App"
    uninstall_steam_launcher_appid "$dir" || exit 1
    rm -rf "$dir"
done
EOF

    [ "$status" -eq 0 ]
}

@test "uninstall_app_is_steam_launcher stays false for a regular shell launcher" {
    app="$HOME/Applications/RegularApp.app"
    create_regular_app "$app"

    run env HOME="$HOME" PROJECT_ROOT="$PROJECT_ROOT" /bin/bash --noprofile --norc <<'EOF'
set -euo pipefail
source "$PROJECT_ROOT/lib/uninstall/steam.sh"
uninstall_app_is_steam_launcher "$HOME/Applications/RegularApp.app" && exit 1
exit 0
EOF

    [ "$status" -eq 0 ]
}

@test "uninstall_steam_launcher_appid rejects URLs in comments or multi-command scripts" {
    app="$HOME/Applications/RegularApp.app"
    create_regular_app "$app"

    cat > "$app/Contents/MacOS/RegularApp" <<'SH'
#!/bin/bash
# open steam://run/1091500
open https://example.com
SH

    run env HOME="$HOME" PROJECT_ROOT="$PROJECT_ROOT" /bin/bash --noprofile --norc <<'EOF'
set -euo pipefail
source "$PROJECT_ROOT/lib/uninstall/steam.sh"
uninstall_steam_launcher_appid "$HOME/Applications/RegularApp.app"
EOF
    [ "$status" -ne 0 ]

    cat > "$app/Contents/MacOS/RegularApp" <<'SH'
#!/bin/bash
open steam://run/1091500
printf 'ordinary app work\n'
SH

    run env HOME="$HOME" PROJECT_ROOT="$PROJECT_ROOT" /bin/bash --noprofile --norc <<'EOF'
set -euo pipefail
source "$PROJECT_ROOT/lib/uninstall/steam.sh"
uninstall_steam_launcher_appid "$HOME/Applications/RegularApp.app"
EOF
    [ "$status" -ne 0 ]
}

@test "uninstall_normalize_size_display hides shortcut size for Steam-managed apps" {
    app="$HOME/Applications/SteamGame.app"
    create_steam_launcher_app "$app" "1091500"

    run env HOME="$HOME" PROJECT_ROOT="$PROJECT_ROOT" /bin/bash --noprofile --norc <<'EOF'
set -euo pipefail
source "$PROJECT_ROOT/lib/core/common.sh"
source "$PROJECT_ROOT/lib/uninstall/steam.sh"
eval "$(sed -n '/^uninstall_normalize_size_display()/,/^}/p' "$PROJECT_ROOT/bin/uninstall.sh")"
printf '%s\n' "$(uninstall_normalize_size_display "93KB" "$HOME/Applications/SteamGame.app")"
printf '%s\n' "$(uninstall_normalize_size_display "--" "$HOME/Applications/SteamGame.app")"
printf '%s\n' "$(uninstall_normalize_size_display "420MB" "$HOME/Applications/RegularApp.app")"
EOF

    [ "$status" -eq 0 ]
    [[ "$output" == *"N/A (Steam-managed)"* ]]
    [[ "$output" != *"93KB"* ]]
}

@test "uninstall selection labels Steam launchers before opening the menu" {
    app="$HOME/Applications/SteamGame.app"
    create_steam_launcher_app "$app" "1091500"

    run env HOME="$HOME" PROJECT_ROOT="$PROJECT_ROOT" TERM="dumb" /bin/bash --noprofile --norc <<'EOF'
set -euo pipefail
source "$PROJECT_ROOT/lib/core/common.sh"
source "$PROJECT_ROOT/lib/uninstall/steam.sh"
source "$PROJECT_ROOT/lib/ui/app_selector.sh"
eval "$(sed -n '/^uninstall_normalize_size_display()/,/^}/p' "$PROJECT_ROOT/bin/uninstall.sh")"

apps_data=("1700000000|$HOME/Applications/SteamGame.app|SteamGame|com.example.steamgame|93KB|Today|95")
selected_apps=()
drain_pending_input() { :; }
paginated_multi_select() {
    printf '%s\n' "$2"
    MOLE_SELECTION_RESULT=""
    return 1
}

select_apps_for_uninstall
EOF

    [ "$status" -ne 0 ]
    [[ "$output" == *"N/A (Steam-managed)"* ]]
    [[ "$output" != *"93KB"* ]]
}

@test "uninstall --list reports Steam launchers as Steam-managed" {
    app="$HOME/Applications/SteamGame.app"
    create_steam_launcher_app "$app" "1091500"
    regular="$HOME/Applications/RegularApp.app"
    create_regular_app "$regular"

    apps_cache="$HOME/apps.cache"
    cat > "$apps_cache" <<CACHE
1700000000|$regular|Regular|com.example.Regular|420MB|Today|430080
1700000000|$app|SteamGame|com.example.steamgame|93KB|Today|95
CACHE

    src="$HOME/uninstall_source.sh"
    sourceable_uninstall_sh "$src"

    run env HOME="$HOME" PROJECT_ROOT="$PROJECT_ROOT" APPS_CACHE_FILE="$apps_cache" SRC_PATH="$src" \
        MOLE_TEST_NO_AUTH=1 MOLE_PLATFORM=darwin /bin/bash --noprofile --norc <<'EOF'
set -euo pipefail
source "$SRC_PATH"

scan_applications() { printf '%s\n' "$APPS_CACHE_FILE"; }
load_applications() {
    apps_data=()
    while IFS='|' read -r epoch app_path app_name bundle_id size last_used size_kb; do
        apps_data+=("$epoch|$app_path|$app_name|$bundle_id|$size|$last_used|${size_kb:-0}")
    done < "$1"
}
is_homebrew_available() { return 1; }
get_brew_cask_name() { return 1; }
log_operation_session_start() { :; }

uninstall_list_apps
EOF

    [ "$status" -eq 0 ] || return 1
    [[ "$output" == *'"name": "SteamGame"'* ]] || return 1
    [[ "$output" == *'"size": "N/A (Steam-managed)"'* ]] || return 1
    [[ "$output" == *'"name": "Regular"'* ]] || return 1
    [[ "$output" == *'"size": "420MB"'* ]]
}

@test "uninstall preview marks Steam launchers as launcher-only" {
    app="$HOME/Applications/SteamGame.app"
    create_steam_launcher_app "$app" "1091500"

    run env HOME="$HOME" PROJECT_ROOT="$PROJECT_ROOT" /bin/bash --noprofile --norc <<'EOF'
set -euo pipefail
source "$PROJECT_ROOT/lib/core/common.sh"
source "$PROJECT_ROOT/lib/uninstall/batch.sh"

get_path_size_kb() { printf '8\n'; }
drain_pending_input() { :; }
request_sudo_access() { return 0; }

app_details=(
    "SteamGame|$HOME/Applications/SteamGame.app|com.example.steamgame|8|||false|false|false|||false||none|||||"
)
running_apps=()
sudo_apps=()
brew_cask_apps=()
total_estimated_size=8

printf '\n' | _batch_preview_and_confirm
EOF

    [ "$status" -eq 0 ] || return 1
    [[ "$output" == *"N/A (Steam-managed)"* ]] || return 1
    [[ "$output" == *"Steam launcher only; game files managed by Steam are not included"* ]]
}
